/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author super
 */
public class Draft extends javax.swing.JFrame {

    /**
     * Creates new form Draft
     */
    File f = new File("text.html");

    public Draft() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            File  f=new File("test.html");            
            BufferedReader bfr = new BufferedReader(new InputStreamReader(new FileInputStream(f))) ;
            
            File fTemp = new File("temp.html");
            FileWriter fw = new FileWriter(fTemp);
            
            String line = null;
            
            while( null != (line = bfr.readLine()) ){
                /* --- */
                line = line.replace("{STRING_REPLACE1}", "Hoang Dong Tien");               
                line = line.replace("{STRING_REPLACE2}", "28"); 
                line = line.replace("{STRING_REPLACE3}", "June"); 
                line = line.replace("{STRING_REPLACE4}", "2015"); 
                line = line.replace("{STRING_REPLACE5}", "HDSE"); 
                line = line.replace("{STRING_REPLACE6}", "285 Đội Cấn"); 
                line = line.replace("{STRING_REPLACE7}", "2015-11-04"); 
                line = line.replace("{STRING_REPLACE8}", "Principal"); 
                fw.write(line);                
            }            
            bfr.close();
            fw.flush();
            fw.close();
            
            
            jTextPane1.setPage(fTemp.toURI().toURL());
            jTextPane1.print();
            
            fTemp.delete();
        } catch (MalformedURLException ex) {
            Logger.getLogger(Draft.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Draft.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PrinterException ex) {
            Logger.getLogger(Draft.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            File  f=new File("test.html");            
            BufferedReader bfr = new BufferedReader(new InputStreamReader(new FileInputStream(f))) ;
            
            File fTemp = new File("temp.html");
            FileWriter fw = new FileWriter(fTemp);
            
            String line = null;
            
            while( null != (line = bfr.readLine()) ){
                /* --- */
                line = line.replace("{STRING_REPLACE1}", "Hoang Dong Tien");               
                line = line.replace("{STRING_REPLACE2}", "28"); 
                line = line.replace("{STRING_REPLACE3}", "June"); 
                line = line.replace("{STRING_REPLACE4}", "2015"); 
                line = line.replace("{STRING_REPLACE5}", "HDSE"); 
                line = line.replace("{STRING_REPLACE6}", "285 Đội Cấn"); 
                line = line.replace("{STRING_REPLACE7}", "2015-11-04"); 
                line = line.replace("{STRING_REPLACE8}", "Principal"); 
                fw.write(line);                
            }            
            bfr.close();
            fw.flush();
            fw.close();
            
            jTextPane1.setPage(fTemp.toURI().toURL());
            
            fTemp.delete();
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(Draft.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Draft.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draft().setVisible(true);
            }
            
            
            
            
            
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
