/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import system.Mark.Mark;

/**
 *
 * @author c1409l3544
 */
public class EnterMarkPage extends javax.swing.JPanel {

    /**
     * Creates new form EnterMarkPage
     * @param CourseID
     */
    DefaultTableModel tblModel;
    public EnterMarkPage(int CourseID) {        
        initComponents();
        tblModel=new DefaultTableModel();
        tblModel.addColumn("Subject");
        tblModel.addColumn("Mark");
        Connection conn=DBConnect.ConnectDatabase();
        try {
            PreparedStatement pre=conn.prepareStatement("select * from subject where courseid=?");
            pre.setInt(1, CourseID);
            ResultSet rs=pre.executeQuery();
            while(rs.next()){
            String[] tempRow={rs.getString("name"),""};
            tblModel.addRow(tempRow);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EnterMarkPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(tblModel);
    }
    
    public List<Mark> getMarkInformation(){
           List<Mark> lstMark=new ArrayList<>();
           return lstMark;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
