/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import java.awt.CardLayout;
import java.awt.Image;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author NamKhanh
 */
public class MainPage extends javax.swing.JFrame {

    //Connection
    private Connection conn = null;
    private CallableStatement stmt = null;
    private ResultSet rs = null;
    public String userID = null;
    public String userName = null;

    CardLayout cardMain;
    JLabel lblAdmin, lblCer, lblStudent, lblSetting, lblHelp;
    int width, height;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        InitOptionControl();
        lblAdmin.setIcon(new ImageIcon(new ImageIcon("src/res/admin.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblCer.setIcon(new ImageIcon(new ImageIcon("src/res/certi.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblStudent.setIcon(new ImageIcon(new ImageIcon("src/res/help.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblSetting.setIcon(new ImageIcon(new ImageIcon("src/res/settings.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblHelp.setIcon(new ImageIcon(new ImageIcon("src/res/student.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblheader.setIcon(new ImageIcon(new ImageIcon("src/res/abclogon.png").getImage().getScaledInstance(75, 75, Image.SCALE_SMOOTH)));
        tabbedPane_Main.setTabComponentAt(0, lblAdmin);
        tabbedPane_Main.setTabComponentAt(1, lblCer);
        tabbedPane_Main.setTabComponentAt(2, lblStudent);
        tabbedPane_Main.setTabComponentAt(3, lblSetting);
        tabbedPane_Main.setTabComponentAt(4, lblHelp);
    }

    private void InitOptionControl() {
        width = 60;
        height = 60;
        cardMain = new CardLayout();
        lblAdmin = new JLabel("Admin");
        lblCer = new JLabel("Certificate Cell");
        lblStudent = new JLabel("Student");
        lblSetting = new JLabel("Settings");
        lblHelp = new JLabel("Help     ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        tabbedPane_Main = new javax.swing.JTabbedPane();
        pnlAdminLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmitAdmin = new javax.swing.JButton();
        txtLoginAdmin = new javax.swing.JTextField();
        passLoginAdmin = new javax.swing.JPasswordField();
        pnlCerLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLoginCer = new javax.swing.JTextField();
        passLoginCer = new javax.swing.JTextField();
        pnlStuLogin = new javax.swing.JPanel();
        pnlSetting = new javax.swing.JPanel();
        pnlHelp = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblheader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane_Main.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        btnSubmitAdmin.setText("Submit");
        btnSubmitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAdminActionPerformed(evt);
            }
        });

        txtLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLoginLayout = new javax.swing.GroupLayout(pnlAdminLogin);
        pnlAdminLogin.setLayout(pnlAdminLoginLayout);
        pnlAdminLoginLayout.setHorizontalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(126, 126, 126)
                        .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(passLoginAdmin)))
                    .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btnSubmitAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        pnlAdminLoginLayout.setVerticalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnSubmitAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        tabbedPane_Main.addTab("tab1", pnlAdminLogin);

        jLabel3.setText("Username:");

        jLabel4.setText("Password");

        javax.swing.GroupLayout pnlCerLoginLayout = new javax.swing.GroupLayout(pnlCerLogin);
        pnlCerLogin.setLayout(pnlCerLoginLayout);
        pnlCerLoginLayout.setHorizontalGroup(
            pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerLoginLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(141, 141, 141)
                .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLoginCer, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(passLoginCer))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        pnlCerLoginLayout.setVerticalGroup(
            pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerLoginLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLoginCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passLoginCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        tabbedPane_Main.addTab("tab2", pnlCerLogin);

        javax.swing.GroupLayout pnlStuLoginLayout = new javax.swing.GroupLayout(pnlStuLogin);
        pnlStuLogin.setLayout(pnlStuLoginLayout);
        pnlStuLoginLayout.setHorizontalGroup(
            pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        pnlStuLoginLayout.setVerticalGroup(
            pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        tabbedPane_Main.addTab("tab3", pnlStuLogin);

        javax.swing.GroupLayout pnlSettingLayout = new javax.swing.GroupLayout(pnlSetting);
        pnlSetting.setLayout(pnlSettingLayout);
        pnlSettingLayout.setHorizontalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        pnlSettingLayout.setVerticalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        tabbedPane_Main.addTab("tab4", pnlSetting);

        javax.swing.GroupLayout pnlHelpLayout = new javax.swing.GroupLayout(pnlHelp);
        pnlHelp.setLayout(pnlHelpLayout);
        pnlHelpLayout.setHorizontalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        pnlHelpLayout.setVerticalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        tabbedPane_Main.addTab("tab5", pnlHelp);

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane_Main)
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPane_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHeader.setBackground(new java.awt.Color(51, 0, 51));

        lblheader.setBackground(new java.awt.Color(51, 0, 51));
        lblheader.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        lblheader.setForeground(new java.awt.Color(0, 51, 255));
        lblheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheader.setText("ABC institute -Certificate Department");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblheader, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAdminActionPerformed

    private void btnSubmitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAdminActionPerformed
        //ADMIN Login
        adminLogin();
    }//GEN-LAST:event_btnSubmitAdminActionPerformed

    public void adminLogin() {
        userID = txtLoginAdmin.getText();
        String pass = new String(passLoginAdmin.getPassword());
        if (txtLoginAdmin.getText().trim().length() <= 0 | pass.trim().length() <= 0) {
            txtLoginAdmin.setText("Username is Required");
            passLoginAdmin.setText("");
        } else if (pass.trim().length() <= 0) {
            //Chờ Label
        } else if (txtLoginAdmin.getText().trim().length() <= 0) {
            //Cho Label
        } else {
            try {
                System.setProperty("user", userID);
                conn = DBConnect.ConnectDatabase();
                stmt = conn.prepareCall("{call AdminLogin(?,?)};");
                stmt.setString(1, userID);
                stmt.setString(2, pass);
                rs = stmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login Successful"); //Dang nhap thanh cong
                    //Cho Form ADMIN
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login Failed");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if(rs!=null)
                        rs.close();
                    if(stmt!=null)
                        stmt.close();
                    if(conn!=null)
                        conn.close();
                } catch (SQLException ex) {
//                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, ex);
                }
            }
        }
    };
    
    
    
    public void cerLogin() {
        userID = txtLoginCer.getText();
        String pass = new String(passLoginAdmin.getPassword());
        if (txtLoginAdmin.getText().trim().length() <= 0 | pass.trim().length() <= 0) {
            txtLoginAdmin.setText("Username is Required");
            passLoginAdmin.setText("");
        } else if (pass.trim().length() <= 0) {
            //Chờ Label
        } else if (txtLoginAdmin.getText().trim().length() <= 0) {
            //Cho Label
        } else {
            try {
                System.setProperty("user", userID);
                conn = DBConnect.ConnectDatabase();
                stmt = conn.prepareCall("{call AdminLogin(?,?)};");
                stmt.setString(1, userID);
                stmt.setString(2, pass);
                rs = stmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login Successful"); //Dang nhap thanh cong
                    //Cho Form ADMIN
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login Failed");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if(rs!=null)
                        rs.close();
                    if(stmt!=null)
                        stmt.close();
                    if(conn!=null)
                        conn.close();
                } catch (SQLException ex) {
//                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, ex);
                }
            }
        }
    };
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblheader;
    private javax.swing.JPasswordField passLoginAdmin;
    private javax.swing.JTextField passLoginCer;
    private javax.swing.JPanel pnlAdminLogin;
    private javax.swing.JPanel pnlCerLogin;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHelp;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JPanel pnlStuLogin;
    private javax.swing.JTabbedPane tabbedPane_Main;
    private javax.swing.JTextField txtLoginAdmin;
    private javax.swing.JTextField txtLoginCer;
    // End of variables declaration//GEN-END:variables
}
