/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import java.awt.CardLayout;
import java.awt.Image;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author NamKhanh
 */
public class MainPage extends javax.swing.JFrame {

    //Connection
    private Connection conn = null;
    private CallableStatement stmt = null;
    private ResultSet rs = null;
    public String userID = null;
    public String userName = null;

    CardLayout cardMain;
    JLabel lblAdmin, lblCer, lblStudent, lblSetting, lblHelp;
    int width, height;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        InitOptionControl();
        lblAdmin.setIcon(new ImageIcon(new ImageIcon("src/res/admin.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblCer.setIcon(new ImageIcon(new ImageIcon("src/res/certi.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblStudent.setIcon(new ImageIcon(new ImageIcon("src/res/help.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblSetting.setIcon(new ImageIcon(new ImageIcon("src/res/settings.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblHelp.setIcon(new ImageIcon(new ImageIcon("src/res/student.png").getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        lblheader.setIcon(new ImageIcon(new ImageIcon("src/res/abclogon.png").getImage().getScaledInstance(75, 75, Image.SCALE_SMOOTH)));
        tabbedPane_Main.setTabComponentAt(0, lblAdmin);
        tabbedPane_Main.setTabComponentAt(1, lblCer);
        tabbedPane_Main.setTabComponentAt(2, lblStudent);
        tabbedPane_Main.setTabComponentAt(3, lblSetting);
        tabbedPane_Main.setTabComponentAt(4, lblHelp);
    }

    private void InitOptionControl() {
        width = 60;
        height = 60;
        cardMain = new CardLayout();
        lblAdmin = new JLabel("Admin");
        lblCer = new JLabel("Certificate Cell");
        lblStudent = new JLabel("Student");
        lblSetting = new JLabel("Settings");
        lblHelp = new JLabel("Help     ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        tabbedPane_Main = new javax.swing.JTabbedPane();
        pnlAdminLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmitAdmin = new javax.swing.JButton();
        txtLoginAdmin = new javax.swing.JTextField();
        passLoginAdmin = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        pnlCerLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtLoginAdmin1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passLoginAdmin1 = new javax.swing.JPasswordField();
        btnSubmitAdmin2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pnlStuLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtLoginAdmin2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passLoginAdmin2 = new javax.swing.JPasswordField();
        btnSubmitAdmin1 = new javax.swing.JButton();
        pnlSetting = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        pnlHelp = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblheader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane_Main.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        btnSubmitAdmin.setText("Submit");
        btnSubmitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAdminActionPerformed(evt);
            }
        });

        txtLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLoginLayout = new javax.swing.GroupLayout(pnlAdminLogin);
        pnlAdminLogin.setLayout(pnlAdminLoginLayout);
        pnlAdminLoginLayout.setHorizontalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btnSubmitAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(126, 126, 126)
                        .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txtLoginAdmin)
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        pnlAdminLoginLayout.setVerticalGroup(
            pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(pnlAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmitAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        tabbedPane_Main.addTab("tab1", pnlAdminLogin);

        jLabel5.setText("Username:");

        txtLoginAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAdmin1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Password:");

        btnSubmitAdmin2.setText("Submit");
        btnSubmitAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAdmin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCerLoginLayout = new javax.swing.GroupLayout(pnlCerLogin);
        pnlCerLogin.setLayout(pnlCerLoginLayout);
        pnlCerLoginLayout.setHorizontalGroup(
            pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerLoginLayout.createSequentialGroup()
                .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCerLoginLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnSubmitAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCerLoginLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5)
                        .addGap(127, 127, 127)
                        .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoginAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCerLoginLayout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(jLabel6)
                    .addGap(126, 126, 126)
                    .addComponent(passLoginAdmin1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGap(155, 155, 155)))
        );
        pnlCerLoginLayout.setVerticalGroup(
            pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerLoginLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(btnSubmitAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCerLoginLayout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addGroup(pnlCerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(passLoginAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(170, Short.MAX_VALUE)))
        );

        tabbedPane_Main.addTab("tab2", pnlCerLogin);

        jLabel7.setText("Username:");

        txtLoginAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAdmin2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Password:");

        btnSubmitAdmin1.setText("Submit");
        btnSubmitAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAdmin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStuLoginLayout = new javax.swing.GroupLayout(pnlStuLogin);
        pnlStuLogin.setLayout(pnlStuLoginLayout);
        pnlStuLoginLayout.setHorizontalGroup(
            pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuLoginLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(126, 126, 126)
                .addGroup(pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoginAdmin2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(passLoginAdmin2))
                .addGap(147, 147, 147))
            .addGroup(pnlStuLoginLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(btnSubmitAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlStuLoginLayout.setVerticalGroup(
            pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuLoginLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLoginAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(pnlStuLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passLoginAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addComponent(btnSubmitAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tabbedPane_Main.addTab("tab3", pnlStuLogin);

        jLabel9.setText("Server Address:");

        jLabel3.setText("Database Name:");

        jLabel4.setText("Username:");

        jLabel12.setText("Password:");

        jButton1.setText("Test");

        jButton2.setText("Ok");

        jLabel14.setText("Port:");

        javax.swing.GroupLayout pnlSettingLayout = new javax.swing.GroupLayout(pnlSetting);
        pnlSetting.setLayout(pnlSettingLayout);
        pnlSettingLayout.setHorizontalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButton1)
                .addGap(106, 106, 106)
                .addComponent(jButton2)
                .addGap(78, 294, Short.MAX_VALUE))
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addGap(42, 42, 42)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jPasswordField1)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSettingLayout.setVerticalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabbedPane_Main.addTab("tab4", pnlSetting);

        javax.swing.GroupLayout pnlHelpLayout = new javax.swing.GroupLayout(pnlHelp);
        pnlHelp.setLayout(pnlHelpLayout);
        pnlHelpLayout.setHorizontalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        pnlHelpLayout.setVerticalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        tabbedPane_Main.addTab("tab5", pnlHelp);

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane_Main)
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPane_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHeader.setBackground(new java.awt.Color(51, 0, 51));

        lblheader.setBackground(new java.awt.Color(51, 0, 51));
        lblheader.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        lblheader.setForeground(new java.awt.Color(0, 51, 255));
        lblheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheader.setText("ABC institute -Certificate Department");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblheader, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAdminActionPerformed

    private void btnSubmitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAdminActionPerformed
        //ADMIN Login
        adminLogin();
    }//GEN-LAST:event_btnSubmitAdminActionPerformed

    private void txtLoginAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAdmin1ActionPerformed

    private void txtLoginAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAdmin2ActionPerformed

    private void btnSubmitAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitAdmin1ActionPerformed

    private void btnSubmitAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitAdmin2ActionPerformed

    public void adminLogin() {
        userID = txtLoginAdmin.getText();
        String pass = new String(passLoginAdmin.getPassword());
        if (txtLoginAdmin.getText().trim().length() <= 0 | pass.trim().length() <= 0) {
            txtLoginAdmin.setText("Username is Required");
            passLoginAdmin.setText("");
        } else if (pass.trim().length() <= 0) {
            //Chờ Label
        } else if (txtLoginAdmin.getText().trim().length() <= 0) {
            //Cho Label
        } else {
            try {
                System.setProperty("user", userID);
                conn = DBConnect.ConnectDatabase();
                stmt = conn.prepareCall("{call AdminLogin(?,?)};");
                stmt.setString(1, userID);
                stmt.setString(2, pass);
                rs = stmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login Successful"); //Dang nhap thanh cong
                    //Cho Form ADMIN
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login Failed");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if(rs!=null)
                        rs.close();
                    if(stmt!=null)
                        stmt.close();
                    if(conn!=null)
                        conn.close();
                } catch (SQLException ex) {
//                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, ex);
                }
            }
        }
    };
    
    
    
    public void cerLogin() {
//        userID = txtLoginCer.getText();
        String pass = new String(passLoginAdmin.getPassword());
        if (txtLoginAdmin.getText().trim().length() <= 0 | pass.trim().length() <= 0) {
            txtLoginAdmin.setText("Username is Required");
            passLoginAdmin.setText("");
        } else if (pass.trim().length() <= 0) {
            //Chờ Label
        } else if (txtLoginAdmin.getText().trim().length() <= 0) {
            //Cho Label
        } else {
            try {
                System.setProperty("user", userID);
                conn = DBConnect.ConnectDatabase();
                stmt = conn.prepareCall("{call AdminLogin(?,?)};");
                stmt.setString(1, userID);
                stmt.setString(2, pass);
                rs = stmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login Successful"); //Dang nhap thanh cong
                    //Cho Form ADMIN
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login Failed");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if(rs!=null)
                        rs.close();
                    if(stmt!=null)
                        stmt.close();
                    if(conn!=null)
                        conn.close();
                } catch (SQLException ex) {
//                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, ex);
                }
            }
        }
    };
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitAdmin;
    private javax.swing.JButton btnSubmitAdmin1;
    private javax.swing.JButton btnSubmitAdmin2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblheader;
    private javax.swing.JPasswordField passLoginAdmin;
    private javax.swing.JPasswordField passLoginAdmin1;
    private javax.swing.JPasswordField passLoginAdmin2;
    private javax.swing.JPanel pnlAdminLogin;
    private javax.swing.JPanel pnlCerLogin;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHelp;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JPanel pnlStuLogin;
    private javax.swing.JTabbedPane tabbedPane_Main;
    private javax.swing.JTextField txtLoginAdmin;
    private javax.swing.JTextField txtLoginAdmin1;
    private javax.swing.JTextField txtLoginAdmin2;
    // End of variables declaration//GEN-END:variables
}
