/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.Certificate;

import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import system.Draft;

/**
 *
 * @author leeja
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        JOptionPane.showMessageDialog(null, "Not supported");
        this.dispose();
        
    }

    public Print(String stringReplace1, String stringReplace2, String stringReplace3, String stringReplace4, String stringReplace5, String stringReplace6, String stringReplace7, String stringReplace8) {
        initComponents();
        string1 = stringReplace1;
        string2 = stringReplace2;
        string3 = stringReplace3;
        string4 = stringReplace4;
        string5 = stringReplace5;
        string6 = stringReplace6;
        string7 = stringReplace7;
        string8 = stringReplace8;
        preloadTemplate();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public String string1;
    public String string2;
    public String string3;
    public String string4;
    public String string5;
    public String string6;
    public String string7;
    public String string8;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print Preview");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 800));

        jScrollPane1.setViewportView(jTextPane1);

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            jTextPane1.print();
            this.dispose();
        } catch (PrinterException ex) {
            Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
            this.dispose();
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    public void preloadTemplate() {
        try {
            File f = new File("templatePrinting.html");
            BufferedReader bfr = new BufferedReader(new InputStreamReader(new FileInputStream(f)));

            File fTemp = new File("temp.html");
            FileWriter fw = new FileWriter(fTemp);

            String line = null;

            while (null != (line = bfr.readLine())) {
                /* --- */
//                line = line.replace("{STRING_REPLACE1}", "Hoang Dong Tien");               
//                line = line.replace("{STRING_REPLACE2}", "28"); 
//                line = line.replace("{STRING_REPLACE3}", "June"); 
//                line = line.replace("{STRING_REPLACE4}", "2015"); 
//                line = line.replace("{STRING_REPLACE5}", "HDSE"); 
//                line = line.replace("{STRING_REPLACE6}", "A"); 
//                line = line.replace("{STRING_REPLACE7}", "2015-11-04"); 
//                line = line.replace("{STRING_REPLACE8}", "Principal"); 

                line = line.replace("{STRING_REPLACE1}", string1);
                line = line.replace("{STRING_REPLACE2}", string2);
                line = line.replace("{STRING_REPLACE3}", string3);
                line = line.replace("{STRING_REPLACE4}", string4);
                line = line.replace("{STRING_REPLACE5}", string5);
                line = line.replace("{STRING_REPLACE6}", string6);
                line = line.replace("{STRING_REPLACE7}", string7);
                line = line.replace("{STRING_REPLACE8}", string8);
                fw.write(line);
            }
            bfr.close();
            fw.flush();
            fw.close();
            jTextPane1.setPage(fTemp.toURI().toURL());

            fTemp.delete();
            this.dispose();
        } catch (MalformedURLException ex) {
            Logger.getLogger(Draft.class.getName()).log(Level.SEVERE, null, ex);

        } catch (IOException ex) {
            Logger.getLogger(Draft.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print("1", "2", "3", "4", "5", "6", "7", "8").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
